### ISSUE TITLE
Futures to add.

### ISSUE THREAD

**Issue by Special-Niewbie** [DigitalAdeel/MaterialSkin2Framework#1]
I'm trying to write it by the phone now. So what can I see that other projects cannot do (including your for now), it's on the Propriety of the object, example the Button it's miss:

Cannot personalize the FillColor of the Actual Base Button Color, what can I see now, I can change just in two colors base Purple and Fuxia but I cannot change to any color.

ImageOffest X-Y of the Icon / Image size.

The BorderColor and Thikness of the Border Button to manage it.

The Ability to change the 4 angles radius of the Button.

The HoverState --> FontColor, Image, BorderColor,FillColor.

The PressedState --> FontColor, Image, BorderColor,FillColor.

And the Animation Circle Color, when you press the actual Button.

These are the ideas that come out in my mind that no one project add and for the Final user prospective it's limitation to don't have such implementation. If you need more Ideas I have others for the Futures. This will make the project really forward in front of others..

*I understand about Material Google colour you can keep as basic, but could be a plus to give the chance to the Developer to add a special section to disable the basic Materials colours and customize it, as the Colour Tone are always to be change in the future.😉

**Comment by Special-Niewbie** [comment]
Thank you @DigitalAdeel to change the label, because by phone was not possible. I saw your answer to another topic Closed and I try to share my point with you here. 

Yes , I complitely understand what you try to tell me and I understood that I can change the color Theme in that way. But with evolving of the looking of the apps, I believe that MateriaSkin in general it's good point to start to make somenthing - in our days -  more advanced.

In visual Style prospective , the MaterialSkin it's good for the effect when you interact with it, for the base font colors to start it's ok, but I can feel it to be a bit agey in our days, because we talk about the style of 2016.
The refresh to call it, maybe MaterialSkin3 o 2 Plus (or keep as it is the name if you want), in our days from the OpenProjects are missing something more personalized in terms of shapes, colors and animation. So , as you know today when you create a program with modern UI you need maybe the buttons that are completely in contrast with the general window style themes or you need to change some crazy theme or need some particular point or details to be completely different color from the rest. 
And what happen when you create the app to visualize it in different ways (if you are limitated with custom Design detail page and you don't have the ability to change immediately the propriety of that object), you feel frustrated; because you need to jump back and forward to each every code section of the object to change a small thing like thikness of the border lines or colors of the border line or shape or anything that can let you to interact more dynamically with the personalization of the UI .😉

**Comment by DigitalAdeel** [comment]
@Special-Niewbie I'll think it about once I'm done with all my freelancing projects :)

**Comment by Special-Niewbie** [comment]
> @Special-Niewbie I'll think it about once I'm done with all my freelancing projects :)

Take your time, no worries, I already appreciate a lot . Keep in touch 🙏

**Comment by DigitalAdeel** [comment]
@Special-Niewbie I'll :)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie Nobody asked for .NET Framework version before, that's why I never had to migrate it back to Framework :)

**Comment by Special-Niewbie** [comment]
> @Special-Niewbie Nobody asked for .NET Framework version before, that's why I never had to migrate it back to Framework :)

I believe you @DigitalAdeel but it's strange to me to hear that, because Framework it's the base of Window to be compatible with different version of Windows OS.... 🤷

**Comment by DigitalAdeel** [comment]
@Special-Niewbie There wasn't any MaterialSkin.2's port for .NET Core 3.1 at that time, so I did it myself 😅

**Comment by DigitalAdeel** [comment]
@Special-Niewbie Thanks for having the courage to ask me for .NET Framework version :)
2 days and 37 downloads
All they had to do was to just ask me for .NET Framework version😆
![image](https://user-images.githubusercontent.com/74082224/221399108-d59443a7-cbf3-4822-9379-8943271efc75.png)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie  Second on 'material' keyword search 😍
![image](https://user-images.githubusercontent.com/74082224/221399356-9ca2ade8-a5c1-49d2-9415-74519d065cb0.png)
 
 and first with additional characters 😍
 
![image](https://user-images.githubusercontent.com/74082224/221399333-1e581de5-6ed1-4128-b98a-cc6d4604e93d.png)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie 
Updated MS2DN Repo's Readme 😘

![image](https://user-images.githubusercontent.com/74082224/221399583-355bf729-5072-41de-9e3d-3d14706d725c.png)

**Comment by Special-Niewbie** [comment]
@DigitalAdeel was completely my pleasure my friend, I wish you the success for the nice person as you are. 
AND I'M Fr**ing sure if you can develop with more flexibility on customisation as I listed you out, your repo will explode..... Yesterday, I tryied to develop the fully personalized button and it works, but if I try to apply in MateriaSkin2 I got many errors because I don't have fully picture and experience to apply my personalised button to MaterialSkin2 or to migrate the "splash" effect animation when you press the button on MaterialSkin2. If you want I can share with you the code of the personalized button and try to apply or add this Splash animation . I do really wish to have the effect animation "splash" of MaterialSkin on my fully personalized button..🙏

**Comment by DigitalAdeel** [comment]
@Special-Niewbie  Updated to motivate others 😅

![image](https://user-images.githubusercontent.com/74082224/221399737-95860e9d-e97b-4aec-9d36-de458d2b6f41.png)

**Comment by DigitalAdeel** [comment]
> @DigitalAdeel was completely my pleasure my friend, I wish you the success for the nice person as you are. AND I'M Fr**ing sure if you can develop with more flexibility on customisation as I listed you out, your repo will explode..... Yesterday, I tryied to develop the fully personalized button and it works, but if I try to apply in MateriaSkin2 I got many errors because I don't have fully picture and experience to apply my personalised button to MaterialSkin2 or to migrate the "splash" effect animation when you press the button on MaterialSkin2. If you want I can share with you the code of the personalized button and try to apply or add this Splash animation . I do really wish to have the effect animation "splash" of MaterialSkin on my fully personalized button..🙏

@Special-Niewbie Sure and Thanks 😘.
My email address is: madeelkd@gmail.com
I'll review the code when I'm free :)

As you can see, atm busy developing clone for my client :)

![image](https://user-images.githubusercontent.com/74082224/221399856-55f5a4f3-c6cf-4620-a4ca-e1efd1f89912.png)

**Comment by Special-Niewbie** [comment]
> > @DigitalAdeel was completely my pleasure my friend, I wish you the success for the nice person as you are. AND I'M Fr**ing sure if you can develop with more flexibility on customisation as I listed you out, your repo will explode..... Yesterday, I tryied to develop the fully personalized button and it works, but if I try to apply in MateriaSkin2 I got many errors because I don't have fully picture and experience to apply my personalised button to MaterialSkin2 or to migrate the "splash" effect animation when you press the button on MaterialSkin2. If you want I can share with you the code of the personalized button and try to apply or add this Splash animation . I do really wish to have the effect animation "splash" of MaterialSkin on my fully personalized button..🙏
> 
> @Special-Niewbie Sure.
> My email address is: madeelkd@gmail.com
> I'll review the code when I'm free :)
> 
> As you can see, atm busy developing clone for my client :)
> 
> ![image](https://user-images.githubusercontent.com/74082224/221399856-55f5a4f3-c6cf-4620-a4ca-e1efd1f89912.png)
> 

Now you make me shed a tear....thank you so much 🙏. Later, when I will be at home in front of the PC, I will  email you and I will attach the file in ".cs" of my personalised button "without the animation splash effect (like MaterialSkin)" because I failed miserably 😅....

**Comment by DigitalAdeel** [comment]
@Special-Niewbie 
![image](https://user-images.githubusercontent.com/74082224/221400161-91636f1f-bf2a-47ce-9ab6-04e5b33e9f6c.png)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie I'm a self learned Full Stack Developer and I also made many mistakes before becoming what I'm now :)

**Comment by Special-Niewbie** [comment]
> @Special-Niewbie I'm a self learned Full Stack Developer and I also made many mistakes before becoming what I'm now :)

Thank you to encourage me , 🙂, the problem of my self it's that I have started to learn 3 language at once....and sometimes I have the head that explode, especially when I'm stuck on something that I don't have yet learned in meantime I try to do something else in parallel.... 🔥

**Comment by DigitalAdeel** [comment]
> > @Special-Niewbie I'm a self learned Full Stack Developer and I also made many mistakes before becoming what I'm now :)
> 
> Thank you to encourage me , 🙂, the problem of my self it's that I have started to learn 3 language at once....and sometimes I have the head that explode, especially when I'm stuck on something that I don't have yet learned in meantime I try to do something else in parallel.... 🔥

Same here but it's better to master 1 language then try to learn all at once 😅
That's what I did, tried python, java, c, c++, visual basic but at the end I went with C#

**Comment by Special-Niewbie** [comment]
> > > @Special-Niewbie I'm a self learned Full Stack Developer and I also made many mistakes before becoming what I'm now :)
> > 
> > Thank you to encourage me , 🙂, the problem of my self it's that I have started to learn 3 language at once....and sometimes I have the head that explode, especially when I'm stuck on something that I don't have yet learned in meantime I try to do something else in parallel.... 🔥
> 
> Same here but it's better to master 1 language then try to learn all at once 😅
> That's what I did, tried python, java, c, c++, visual basic but at the end I went with C#

I have a big defect.... I'm too ambitious 😅

**Comment by DigitalAdeel** [comment]
> > > > @Special-Niewbie I'm a self learned Full Stack Developer and I also made many mistakes before becoming what I'm now :)
> > > 
> > > 
> > > Thank you to encourage me , 🙂, the problem of my self it's that I have started to learn 3 language at once....and sometimes I have the head that explode, especially when I'm stuck on something that I don't have yet learned in meantime I try to do something else in parallel.... 🔥
> > 
> > 
> > Same here but it's better to master 1 language then try to learn all at once 😅
> > That's what I did, tried python, java, c, c++, visual basic but at the end I went with C#
> 
> I have a big defect.... I'm too ambitious 😅

https://youtu.be/kku2LAwSfaI?t=13
from 13 seconds till 21 is the answer about you being too ambitious 😆
